In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

In [2]:
warnings.filterwarnings('ignore')
%matplotlib inline
%config InlineBackend.figure_format = 'svg'

In [3]:
df_train = pd.read_csv('train.csv', delimiter =',')
df_train.head(3)

Id   age  years_of_experience  lesson_price  qualification  physics  \
0   0  40.0                  0.0        1400.0            1.0      1.0   
1   1  48.0                  4.0        2850.0            3.0      1.0   
2   2  39.0                  0.0        1200.0            1.0      0.0   

   chemistry  biology  english  geography  history  mean_exam_points  
0        0.0      0.0      0.0        1.0      0.0                61  
1        0.0      0.0      0.0        0.0      0.0                76  
2        0.0      0.0      0.0        0.0      0.0                53

In [4]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Id                   10000 non-null  int64  
 1   age                  10000 non-null  float64
 2   years_of_experience  10000 non-null  float64
 3   lesson_price         10000 non-null  float64
 4   qualification        10000 non-null  float64
 5   physics              10000 non-null  float64
 6   chemistry            10000 non-null  float64
 7   biology              10000 non-null  float64
 8   english              10000 non-null  float64
 9   geography            10000 non-null  float64
 10  history              10000 non-null  float64
 11  mean_exam_points     10000 non-null  int64  
dtypes: float64(10), int64(2)
memory usage: 937.6 KB


In [5]:
df_train.describe()

Id           age  years_of_experience  lesson_price  \
count  10000.00000  10000.000000         10000.000000  10000.000000   
mean    4999.50000     45.878000             1.986800   1699.105000   
std     2886.89568      8.043929             1.772213    524.886654   
min        0.00000     23.000000             0.000000    200.000000   
25%     2499.75000     40.000000             0.000000   1300.000000   
50%     4999.50000     46.000000             2.000000   1500.000000   
75%     7499.25000     51.000000             3.000000   2150.000000   
max     9999.00000     68.000000            10.000000   3950.000000   

       qualification       physics     chemistry       biology       english  \
count   10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean        1.719500      0.375000      0.132900      0.109600      0.053700   
std         0.792264      0.484147      0.339484      0.312406      0.225436   
min         1.000000      0.000000      0.000000      0.000000      0.000000   
25%         1.000000      0.000000      0.000000      0.000000      0.000000   
50%         2.000000      0.000000      0.000000      0.000000      0.000000   
75%         2.000000      1.000000      0.000000      0.000000      0.000000   
max         4.000000      1.000000      1.000000      1.000000      1.000000   

          geography       history  mean_exam_points  
count  10000.000000  10000.000000      10000.000000  
mean       0.032100      0.019400         63.737300  
std        0.176274      0.137933         14.705574  
min        0.000000      0.000000         32.000000  
25%        0.000000      0.000000         53.000000  
50%        0.000000      0.000000         63.000000  
75%        0.000000      0.000000         74.000000  
max        1.000000      1.000000        100.000000

In [6]:
print(df_train.nunique())

Id                     10000
age                       46
years_of_experience       11
lesson_price              74
qualification              4
physics                    2
chemistry                  2
biology                    2
english                    2
geography                  2
history                    2
mean_exam_points          69
dtype: int64


In [7]:
X = pd.DataFrame(df_train)
y = pd.DataFrame(X, columns=['mean_exam_points'])
X.drop(['Id','mean_exam_points'], axis=1, inplace=True)

In [8]:
y = y.to_numpy()

In [9]:
y = y.ravel()
y

array([61, 76, 53, ..., 62, 56, 52], dtype=int64)

In [10]:
X = X.to_numpy()

In [11]:
X[:, 1].min(), X[:, 1].max()

(0.0, 10.0)

In [12]:
X[:, 2].min(), X[:, 2].max()

(200.0, 3950.0)

In [13]:
def min_max_scale(X):
    return (X - X.min()) / (X.max() - X.min())

In [52]:
X_norm = X.copy()
X_norm = X_norm.astype(np.float64)
X_norm[:, 0] = min_max_scale(X_norm[:, 0])
#X_norm[:, 1] = min_max_scale(X_norm[:, 1])
X_norm[:, 2] = min_max_scale(X_norm[:, 2])
#X_norm[:, 3] = min_max_scale(X_norm[:, 3])
#X_norm[:, 4] = min_max_scale(X_norm[:, 4])
#X_norm[:, 5] = min_max_scale(X_norm[:, 5])
#X_norm[:, 6] = min_max_scale(X_norm[:, 6])
#X_norm[:, 7] = min_max_scale(X_norm[:, 7])
#X_norm[:, 8] = min_max_scale(X_norm[:, 8])
#X_norm[:, 9] = min_max_scale(X_norm[:, 9])
X_norm

array([[0.37777778, 0.        , 0.32      , ..., 0.        , 1.        ,
        0.        ],
       [0.55555556, 4.        , 0.70666667, ..., 0.        , 0.        ,
        0.        ],
       [0.35555556, 0.        , 0.26666667, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.24444444, 1.        , 0.28      , ..., 0.        , 0.        ,
        0.        ],
       [0.22222222, 3.        , 0.24      , ..., 0.        , 0.        ,
        0.        ],
       [0.26666667, 0.        , 0.33333333, ..., 0.        , 0.        ,
        0.        ]])

In [15]:
def standard_scale(X):
    mean = X.mean()
    std = X.std()
    return (X - mean) / std

In [64]:
from sklearn.metrics import r2_score

In [53]:
X_st = X.copy().astype(np.float64)
X_st[:, 0] = standard_scale(X_st[:, 0])
#X_st[:, 1] = standard_scale(X_st[:, 1])
X_st[:, 2] = standard_scale(X_st[:, 2])
#X_st[:, 3] = standard_scale(X_st[:, 3])
#X_st[:, 4] = standard_scale(X_st[:, 4])
#X_st[:, 5] = standard_scale(X_st[:, 5])
#X_st[:, 6] = standard_scale(X_st[:, 6])
#X_st[:, 7] = standard_scale(X_st[:, 7])
#X_st[:, 8] = standard_scale(X_st[:, 8])
#X_st[:, 9] = standard_scale(X_st[:, 9])
X_st

array([[-0.73077401,  0.        , -0.56987533, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.26381464,  4.        ,  2.19276398, ...,  0.        ,
         0.        ,  0.        ],
       [-0.85509759,  0.        , -0.95092903, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.4767155 ,  1.        , -0.85566561, ...,  0.        ,
         0.        ,  0.        ],
       [-1.60103908,  3.        , -1.14145588, ...,  0.        ,
         0.        ,  0.        ],
       [-1.35239192,  0.        , -0.47461191, ...,  0.        ,
         0.        ,  0.        ]])

In [17]:
def calc_mae(y, y_pred):
    err = np.mean(np.abs(y - y_pred))
    return err

def calc_mse(y, y_pred):
    err = np.mean((y - y_pred)**2)
    return err

In [116]:
# стохастический градиентный спуск
def stohastic_gradient_descent(X, y, iterations, batch_size, eta=0.7e-1):
    W = np.random.randn(X.shape[1])
    #W = np.array([0.5, 0.2, 0.02, 2.1, 1.9, 0.95, 1, 0.98, 0.95, 0.95])
    n = X.shape[0]
    
    n_batch = n // batch_size    
    if n % batch_size != 0:
        n_batch += 1
    print(f'amount of batches is {n_batch}')
        
    for i in range(0, iterations):
        
        for b in range(n_batch):
            start = batch_size * b
            end = batch_size * (b + 1)
            
#             print(b, start, end)
            
            X_tmp = X[start : end, ]
            y_tmp = y[start : end]

            err = calc_mse(y, np.dot(X, W))
            
            y_pred_tmp = np.dot(X_tmp, W)
            dQ = 2/len(y_tmp) * X_tmp.T @ (y_pred_tmp - y_tmp) # градиент функции ошибки
            W -= (eta * dQ)
        
        if i % (iterations / 10) == 0:
            print(f'Iter: {i}, weights: {W}, error {err}')
    
    print(f'Final MSE: {calc_mse(y, np.dot(X, W))}')
    return W

In [117]:
W = stohastic_gradient_descent(X, y, iterations=1000, batch_size=7, eta=1e-8)

amount of batches is 1429
Iter: 0, weights: [-0.66829113  0.69898515  0.05163573 -1.27409854  1.47279355  1.15400247
 -0.15349078 -0.40622958 -1.12127973  0.15350463], error 485.2137449027941
Iter: 100, weights: [-0.07851601  0.70177754  0.03753801 -1.27097621  1.47977742  1.15517587
 -0.15174899 -0.40533211 -1.12081028  0.15375535], error 228.3446862994275
Iter: 200, weights: [ 0.2108398   0.70079918  0.03062034 -1.26639715  1.48487288  1.15572629
 -0.15054303 -0.40470897 -1.1204881   0.15389402], error 166.3722036904798
Iter: 300, weights: [ 0.35282058  0.69799061  0.02722492 -1.26110556  1.48904085  1.1559711
 -0.14960003 -0.40422046 -1.1202382   0.15397776], error 151.3633410031022
Iter: 400, weights: [ 0.42250429  0.69430364  0.02555738 -1.25546652  1.49275272  1.15606602
 -0.1487861  -0.40379804 -1.1200238   0.15403459], error 147.68661594018124
Iter: 500, weights: [ 0.45672144  0.69020503  0.02473746 -1.24965914  1.49623974  1.15608743
 -0.14803559 -0.4034081  -1.11982684  0.154

In [85]:
X.shape,  W.shape, y.shape

((10000, 10), (10,), (10000,))

In [141]:
def gradient_descent_reg_l1(X, y, iterations, eta=1e-2, reg=1e-8):
    #W = np.random.randn(X.shape[1])
   # W = np.array([0.5, 0.2, 0.02, 2.1, 1.9, 0.95, 1, 0.98, 0.95, 0.95])
    W = np.array([0.50472281, 0.15494133, 0.01734904, 4.75195366, 4.05232883,
       0.96694905, 1.31193872, 1.11594182, 0.93758239, 0.92981086])
    n = X.shape[0]
    
    for i in range(0, iterations):
        y_pred = np.dot(X, W)
        err = calc_mse(y, y_pred)
        
        dQ = 2/n * X.T @ (y_pred - y) # градиент функции ошибки
        dReg = reg * np.sign(W) # градиент регуляризации
        
        W -= eta * (dQ + dReg)
        
        if i % (iterations / 10) == 0:
            print(f'Iter: {i}, weights: {W}, error {err}')
    
    print(f'Final MSE: {calc_mse(y, np.dot(X, W))}')
    return W

In [149]:
W = gradient_descent_reg_l1(X, y, iterations=3000000, eta=3.1e-7, reg=1e-2)

Iter: 0, weights: [0.50494981 0.15554067 0.01786298 4.31880317 3.70110298 0.96429133
 1.25086387 1.088486   0.93983048 0.93399988], error 124.95960575002196
Iter: 300000, weights: [0.50487945 0.15534163 0.01770072 4.45556917 3.8120205  0.96513776
 1.26955409 1.09683532 0.93913318 0.93273366], error 124.61886636321265
Iter: 600000, weights: [0.50481104 0.15516114 0.01754552 4.58637368 3.9180873  0.96594127
 1.28792696 1.10508743 0.9384558  0.9314757 ], error 124.30685840986297
Iter: 900000, weights: [0.50474455 0.15499439 0.01739707 4.71147674 4.01951534 0.96670372
 1.30598729 1.11324396 0.93779763 0.93022576], error 124.02114106074113
Iter: 1200000, weights: [0.50467995 0.15483848 0.01725509 4.83112702 4.11650735 0.96742688
 1.32373987 1.12130652 0.93715797 0.92898361], error 123.75948145321034
Iter: 1500000, weights: [0.50461717 0.1546916  0.01711928 4.94556237 4.20925717 0.96811244
 1.3411894  1.12927666 0.93653613 0.92774903], error 123.51983695318643
Iter: 1800000, weights: [0.5045

In [150]:
W

array([0.50432888, 0.15406193, 0.01652391, 5.44713733, 4.61558586,
       0.97103095, 1.42405336, 1.1677924 , 0.93367268, 0.9216829 ])

In [151]:
df_test = pd.read_csv('test.csv', delimiter =',')
df_test.head(3)

Id   age  years_of_experience  lesson_price  qualification  physics  \
0  10000  46.0                  3.0        1050.0            1.0      0.0   
1  10001  43.0                  3.0        1850.0            2.0      0.0   
2  10002  52.0                  1.0        1550.0            1.0      1.0   

   chemistry  biology  english  geography  history  
0        1.0      0.0      0.0        0.0      0.0  
1        0.0      0.0      0.0        0.0      0.0  
2        0.0      0.0      0.0        0.0      0.0

In [152]:
X_test = pd.DataFrame(df_test)
X_test.drop(['Id'], axis=1, inplace=True)
X_test = X_test.to_numpy()

In [105]:
X_test_norm = X_test.copy()
X_test_norm = X_norm.astype(np.float64)
X_test_norm

array([[0.37777778, 0.        , 0.32      , ..., 0.        , 1.        ,
        0.        ],
       [0.55555556, 4.        , 0.70666667, ..., 0.        , 0.        ,
        0.        ],
       [0.35555556, 0.        , 0.26666667, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.24444444, 1.        , 0.28      , ..., 0.        , 0.        ,
        0.        ],
       [0.22222222, 3.        , 0.24      , ..., 0.        , 0.        ,
        0.        ],
       [0.26666667, 0.        , 0.33333333, ..., 0.        , 0.        ,
        0.        ]])

In [95]:
X_test_norm[:, 0] = min_max_scale(X_test_norm[:, 0])
#X_test_norm[:, 1] = min_max_scale(X_test_norm[:, 1])
X_test_norm[:, 2] = min_max_scale(X_test_norm[:, 2])
#X_test_norm[:, 3] = min_max_scale(X_test_norm[:, 3])
#X_test_norm[:, 4] = min_max_scale(X_test_norm[:, 4])
#X_test_norm

In [153]:
predictions = np.dot(X_test, W)
predictions

array([47.42958921, 63.61183771, 62.05394903, ..., 41.03660219,
       64.01890523, 74.04010737])

In [154]:
r2_score(y, predictions)

-0.8413749687030192

In [155]:
submit = pd.read_csv('sample_submission.csv', delimiter =',')
submit.head(3)

Id  mean_exam_points
0  10000              50.0
1  10001              50.0
2  10002              50.0

In [156]:
submit['mean_exam_points'] = predictions
submit.head()

Id  mean_exam_points
0  10000         47.429589
1  10001         63.611838
2  10002         62.053949
3  10003         99.971511
4  10004         95.814036

In [157]:
submit.to_csv('csv_to_submit.csv', index=False)