In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

In [2]:
warnings.filterwarnings('ignore')
%matplotlib inline
%config InlineBackend.figure_format = 'svg'

In [82]:
df_train = pd.read_csv('train.csv', delimiter =',')
df_train.head(3)

Id   age  years_of_experience  lesson_price  qualification  physics  \
0   0  40.0                  0.0        1400.0            1.0      1.0   
1   1  48.0                  4.0        2850.0            3.0      1.0   
2   2  39.0                  0.0        1200.0            1.0      0.0   

   chemistry  biology  english  geography  history  mean_exam_points  
0        0.0      0.0      0.0        1.0      0.0                61  
1        0.0      0.0      0.0        0.0      0.0                76  
2        0.0      0.0      0.0        0.0      0.0                53

In [83]:
data = np.genfromtxt('train.csv', delimiter =',', names=True)

In [84]:
data

array([(0.000e+00, 40., 0., 1400., 1., 1., 0., 0., 0., 1., 0., 61.),
       (1.000e+00, 48., 4., 2850., 3., 1., 0., 0., 0., 0., 0., 76.),
       (2.000e+00, 39., 0., 1200., 1., 0., 0., 0., 0., 0., 0., 53.), ...,
       (9.997e+03, 34., 1., 1250., 1., 1., 0., 0., 0., 0., 0., 62.),
       (9.998e+03, 33., 3., 1100., 1., 0., 0., 0., 0., 0., 0., 56.),
       (9.999e+03, 35., 0., 1450., 1., 0., 0., 0., 0., 0., 0., 52.)],
      dtype=[('Id', '<f8'), ('age', '<f8'), ('years_of_experience', '<f8'), ('lesson_price', '<f8'), ('qualification', '<f8'), ('physics', '<f8'), ('chemistry', '<f8'), ('biology', '<f8'), ('english', '<f8'), ('geography', '<f8'), ('history', '<f8'), ('mean_exam_points', '<f8')])

In [85]:
data.shape

(10000,)

In [86]:
a = data.reshape((10000, 10))

ValueError: cannot reshape array of size 10000 into shape (10000,10)

In [87]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Id                   10000 non-null  int64  
 1   age                  10000 non-null  float64
 2   years_of_experience  10000 non-null  float64
 3   lesson_price         10000 non-null  float64
 4   qualification        10000 non-null  float64
 5   physics              10000 non-null  float64
 6   chemistry            10000 non-null  float64
 7   biology              10000 non-null  float64
 8   english              10000 non-null  float64
 9   geography            10000 non-null  float64
 10  history              10000 non-null  float64
 11  mean_exam_points     10000 non-null  int64  
dtypes: float64(10), int64(2)
memory usage: 937.6 KB


In [88]:
df_train.describe()

Id           age  years_of_experience  lesson_price  \
count  10000.00000  10000.000000         10000.000000  10000.000000   
mean    4999.50000     45.878000             1.986800   1699.105000   
std     2886.89568      8.043929             1.772213    524.886654   
min        0.00000     23.000000             0.000000    200.000000   
25%     2499.75000     40.000000             0.000000   1300.000000   
50%     4999.50000     46.000000             2.000000   1500.000000   
75%     7499.25000     51.000000             3.000000   2150.000000   
max     9999.00000     68.000000            10.000000   3950.000000   

       qualification       physics     chemistry       biology       english  \
count   10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean        1.719500      0.375000      0.132900      0.109600      0.053700   
std         0.792264      0.484147      0.339484      0.312406      0.225436   
min         1.000000      0.000000      0.000000      0.000000      0.000000   
25%         1.000000      0.000000      0.000000      0.000000      0.000000   
50%         2.000000      0.000000      0.000000      0.000000      0.000000   
75%         2.000000      1.000000      0.000000      0.000000      0.000000   
max         4.000000      1.000000      1.000000      1.000000      1.000000   

          geography       history  mean_exam_points  
count  10000.000000  10000.000000      10000.000000  
mean       0.032100      0.019400         63.737300  
std        0.176274      0.137933         14.705574  
min        0.000000      0.000000         32.000000  
25%        0.000000      0.000000         53.000000  
50%        0.000000      0.000000         63.000000  
75%        0.000000      0.000000         74.000000  
max        1.000000      1.000000        100.000000

In [89]:
print(df_train.nunique())

Id                     10000
age                       46
years_of_experience       11
lesson_price              74
qualification              4
physics                    2
chemistry                  2
biology                    2
english                    2
geography                  2
history                    2
mean_exam_points          69
dtype: int64


In [90]:
X = pd.DataFrame(df_train)
y = pd.DataFrame(X, columns=['mean_exam_points'])
X.drop(['Id','mean_exam_points'], axis=1, inplace=True)

In [108]:
A = X.to_numpy()
A

array([[4.00e+01, 0.00e+00, 1.40e+03, ..., 0.00e+00, 1.00e+00, 0.00e+00],
       [4.80e+01, 4.00e+00, 2.85e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       [3.90e+01, 0.00e+00, 1.20e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       ...,
       [3.40e+01, 1.00e+00, 1.25e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       [3.30e+01, 3.00e+00, 1.10e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       [3.50e+01, 0.00e+00, 1.45e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00]])

In [109]:
B = y.to_numpy()
B

array([[61],
       [76],
       [53],
       ...,
       [62],
       [56],
       [52]], dtype=int64)

In [91]:
# реализуем функцию, определяющую среднеквадратичную ошибку
def mserror(X, w, y_pred):
    y = X.dot(w)
    return (sum((y - y_pred)**2)) / len(y)

In [92]:
def normal_equation(X, y):
    return np.linalg.solve((X.T).dot(X), (X.T).dot(y))

In [110]:
normal_eq_w = normal_equation(A, B)
#print(f'В случае использования нормального уравнения функционал ошибки составляет {round(mserror(X, normal_eq_w, y), 4)}')
normal_eq_w 

array([[0.50143256],
       [0.15423131],
       [0.01409004],
       [7.48412148],
       [6.25062643],
       [1.00776002],
       [2.35723941],
       [2.01518636],
       [1.06553389],
       [0.85071555]])

In [111]:
y1 = A.dot(normal_eq_w)

In [112]:
y1

array([[54.58364346],
       [93.54529948],
       [43.94804214],
       ...,
       [48.55023916],
       [39.99313646],
       [45.46482243]])

In [118]:
(y1 - B)**2

array([[ 41.16963127],
       [307.83753399],
       [ 81.93794119],
       ...,
       [180.89606656],
       [256.21968041],
       [ 42.70854587]])

In [114]:
mserror(A, normal_eq_w, B)

array([120.83188958])